# Generated by Django 4.1 on 2022-08-22 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mkhome', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='account',
            managers=[
            ],
        ),
    ]
