# Generated by Django 4.1 on 2022-08-22 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mkhome', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='account',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='account',
            old_name='date_joined',
            new_name='date_joined',
        ),
    ]
