# Generated by Django 4.1 on 2022-09-05 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mkhome', '0002_alter_account_managers'),
        ('mkhome', '0002_alter_account_managers_and_more'),
    ]

    operations = [
    ]
