# Generated by Django 4.0.6 on 2022-09-29 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_confirmed', models.BooleanField(default=False)),
                ('order_confirmed_date', models.DateTimeField(blank=True, null=True)),
                ('Shipped', models.BooleanField(default=False)),
                ('Shipped_date', models.DateTimeField(blank=True, null=True)),
                ('out_for_delivery', models.BooleanField(default=False)),
                ('out_for_delivery_date', models.DateTimeField(blank=True, null=True)),
                ('delivered', models.BooleanField(default=False)),
                ('delivered_date', models.DateTimeField(blank=True, null=True)),
                ('Cancelled', models.BooleanField(default=False)),
                ('cancelled_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_order_status', to='orders.order')),
            ],
        ),
    ]
